import test from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
import {databaseEnabled,getPool} from '../server/db.js'
test('Master Site API persists shared source and independent upload history',{skip:!databaseEnabled},async()=>{
  assert.equal(process.env.DB_NAME,'pm_site_modular_test')
  const database='pm_master_test_'+crypto.randomUUID().replaceAll('-','')
  await getPool().query(`CREATE DATABASE ${database}`)
  const script=`import assert from 'node:assert/strict';import ExcelJS from 'exceljs';import app from './server/index.js';import {getPool} from './server/db.js';import {siteData,analyzeSite} from './server/pm-site.js';const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;try{const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet('Master');sheet.addRow(['Site ID','Site Name','LAT','LON','NOP']);sheet.addRow(['TEST001','Master shared name',1,100,'Test NOP']);const form=new FormData();form.append('file',new Blob([await workbook.xlsx.writeBuffer()]),'Master Site.xlsx');form.append('upload_date','2026-09-18');const response=await fetch(base+'/api/pm-site/sources/master',{method:'POST',body:form});assert.equal(response.status,200);assert.equal((await response.json()).row_count,1);const latest=await (await fetch(base+'/api/master-site/upload')).json();assert.equal(latest.latest_upload.filename,'Master Site.xlsx');const history=await (await fetch(base+'/api/uploads?page=master')).json();assert.equal(history.items.length,1);assert.equal(history.items[0].upload_date,'2026-09-18');const other=await (await fetch(base+'/api/uploads?page=site')).json();assert.equal(other.items.length,0);const data=await siteData();assert.equal(data.master[0].site_name,'Master shared name');const detail=analyzeSite({site_id:'TEST001',schedule_date:'2026-09-18',maintenance_kind:'site'},data);assert.equal(detail.master.site_name,'Master shared name');assert.equal((await getPool().query('SELECT COUNT(*) AS n FROM pm_site_source_rows'))[0][0].n,1);for(const [kind,headers,values] of [['ggr',['Site','Ticket No','Period Down'],['TEST001','GGR001','2026-09-18']],['inap',['Site','TT Number','Occured Time'],['TEST001','INAP001','2026-09-18']],['swfm',['Site ID','Ticket Number SWFM','Occured Time'],['TEST001','SWFM001','2026-09-18']]]){const book=new ExcelJS.Workbook();const tab=book.addWorksheet('Source');tab.addRow(headers);tab.addRow(values);const body=new FormData();body.append('file',new Blob([await book.xlsx.writeBuffer()]),kind+'.xlsx');body.append('upload_date','2026-09-18');const res=await fetch(base+'/api/pm-site/sources/'+kind,{method:'POST',body});assert.equal(res.status,200,kind);const history=await(await fetch(base+'/api/uploads?page='+kind)).json();assert.equal(history.items.length,1);assert.equal(history.items[0].filename,kind+'.xlsx');}const freshness=await(await fetch(base+'/api/data-freshness')).json();assert.equal(freshness.items.length,8);for(const kind of ['master','ggr','inap','swfm'])assert.equal(freshness.items.find(row=>row.key===kind).latest.upload_date,'2026-09-18');assert.equal(freshness.items.find(row=>row.key==='dashboard').latest,null);}finally{await new Promise(r=>server.close(r));await getPool().end();}`
  try{await promisify(execFile)(process.execPath,['--input-type=module','-e',script],{cwd:new URL('../',import.meta.url),env:{...process.env,DB_NAME:database}})}finally{await getPool().query(`DROP DATABASE ${database}`);await getPool().end()}
})
